### ISSUE TITLE
bug: Multiple OpenEVSEs not addressed by device_id correctly in set_override and clear_override

### ISSUE THREAD

**Issue by fhteagle** [firstof9/openevse#156]
I now have two OpenEVSE's on my LAN:

- 1756evse has device id beginning with a6d4, ip ends in .72
- 2691evse has device id beginning with b916, ip ends in .73

Using set_override service call in an automation or in developer service test screen, 2691evse is always affected. Even after I checked that the device_id value was correctly set to the device id beginning with a6d4 in the YAML view to try to address 1756evse, in all cases 2691evse is actually changed by the service call.

I also verified that the host/IP values are correct for each OpenEVSE device in the integration configuration, so that is not the cause of the issue.

**Comment by firstof9** [comment]
How are you calling it?

**Comment by fhteagle** [comment]
Here is an example YAML that I used in both a test automation and in Developer Tools > Service tab:

```service: openevse.set_override
data:
  state: disabled
  auto_release: true
target:
  device_id: a6d4....................................  ```

(actual value for device_id censored for github post, but is correct in YAML)

Does not matter if trying to do state: active, if auto_release is set, charge_current is set, etc. In all cases device_id b916 is affected even if a6d4 is specified in YAML or correct entity is shown in GUI mode.

**Comment by fhteagle** [comment]
Diagnostic json output in case it helps:

https://pastebin.com/Z3Jz1VEN

**Comment by firstof9** [comment]
Ya that shouldn't be the case, I'll take a look.

**Comment by fhteagle** [comment]
Further troubleshooting: when selecting any of:

- switch.1756evse_manual_override
- switch.1756evse_sleep_mode
- select.1756evse_max_current
- switch.2691evse_manual_override
- switch.2691evse_sleep_mode
- select.2691evse_max_current

The correct device is affected. It seems to only be the set_override service call that is misbehaving as far as I can tell.

Thanks.

**Comment by firstof9** [comment]
Could you test the potential fix with the https://github.com/firstof9/openevse/tree/services-fix branch?
Thanks

**Comment by fhteagle** [comment]
I manually downloaded the services fix branch zip, unzipped, replaced custom_components/openevse directory, removed old devices, restarted HA, re-added devices, tested in developer services tab..... but the behavior remains the same. The last added device remains the target of the set_override service call.

**Comment by firstof9** [comment]
Very odd, I'll keep looking

**Comment by firstof9** [comment]
Does the `clear_override` also hit the first device only?

**Comment by fhteagle** [comment]
With both the main and service fix branches, clear_override hits the _last_ added device only.

**Comment by fhteagle** [comment]
I pulled the service fix code change from yesterday. I am now seeing "Failed to call service openevse.clear_override. Unknown error" as the popup reply when trying clear_override service call, and a similar message for set_override. Neither EVSE is affected by set_override or clear_override service calls now.

Here is what I think are the relevant log entries: https://pastebin.com/wb4eKQQS

**Comment by firstof9** [comment]
Yup looks like I missed a step, I've pushed a new commit, that should fix it up.

**Comment by fhteagle** [comment]
set_override and clear_override are still failing, but with a different log message now:

https://pastebin.com/L2khz8M9

I removed and re-added devices, restarted HA just to be sure it was not cruft, but the above logged error continues to happen.

**Comment by fhteagle** [comment]
Just tried 2.1.17, no change in this bug. Let me know if there's anything else you want me to try. logs you need, etc.

Thanks.

**Comment by firstof9** [comment]
I'm still looking into this, I think I have an idea to solve it.

**Comment by firstof9** [comment]
Just to confirm, the latest from https://github.com/firstof9/openevse/tree/services-fix branch doesn't help?

**Comment by fhteagle** [comment]
I just tested services-fix branch again. Appears to be the same error.

Relevant log lines:
https://pastebin.com/Ehz12PsU

**Comment by firstof9** [comment]
Ok I've updated the branch again, please see if this has resolved this issue.

Thanks again for testing.

**Comment by fhteagle** [comment]
Swapped back to main branch release 2.1.18, re-tested, everything still seems in order. Thanks for the fix.
